### ISSUE TITLE
ORTF front direction sample offset (left-right)

### ISSUE THREAD

**Issue by m-r-s** [HoerTech-gGmbH/tascar#2]
I observed that there was an (1-off) sample offset between the left and the right channel signal with the ORTF receiver when there should be none (for the front direction).

Maybe some round/ceil/floor issue?
Or is this expected?

I attached the scene description:
[example.zip](https://github.com/HoerTech-gGmbH/tascar/files/3176116/example.zip)

**Comment by gisogrimm** [comment]
Solved by latest commit (incomplete convergence of linear interpolation due to rounding errors)
