### ISSUE TITLE
Install on Ubuntu 20.10

### ISSUE THREAD

**Issue by m-r-s** [HoerTech-gGmbH/tascar#3]
I tried to install tascar on Ubuntu 20.10 from the focal repository and it failed due to an unmet dependency.

Will there be (at least unofficial) support for Ubuntu 20.10 or will I have to compile it myself?

marc@mini:~$ sudo apt install tascarpro
[sudo] Passwort für marc: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libtascar : Hängt ab von: libgsl23 ist aber nicht installierbar oder
                            libgsl2 ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

**Comment by tobiasherzke** [comment]
As a workaround, it should be possible to add 
`deb http://de.archive.ubuntu.com/ubuntu/ focal main restricted`
as an additional source to /etc/apt/sources.list and have the dependency resolved this way.

**Comment by gisogrimm** [comment]
Could you please let me know which version of libgsl is available on Ubuntu 20.10?
Officially only LTS versions ob Ubuntu are (and will be) supported.

**Comment by gisogrimm** [comment]
I added libgsl25 to the possible candidates. Debian packages will be available at about 11am CEST (development branch for now).

**Comment by m-r-s** [comment]
Wow, you guys are fast :)
Installation now works!

Tascar still tries to use the libgsl.so.23 which I needed to work around with a link:

`marc@mini:/usr/lib/x86_64-linux-gnu$ sudo ln -s libgsl.so.25 libgsl.so.23`

Thanks!

**Comment by tobiasherzke** [comment]
* This issue has been resolved.
* Ubuntu 20.10 is past end-of-life.
* For long-term solution, see #8.
