### ISSUE TITLE
Missing dependency for tascar_renderfile: "libboost-program-options1.71.0"

### ISSUE THREAD

**Issue by m-r-s** [HoerTech-gGmbH/tascar#4]
tascar_renderfile needs "libboost-program-options1.71.0" which is not installed when installing "tascarpro".

The resulting error message is:
`tascar_renderfile: error while loading shared libraries: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory`
Installing "libboost-program-options1.71.0" manually solved the problem

**Comment by gisogrimm** [comment]
tascarcli.deb depends on "libboost-program-options1.65.1 | libboost-program-options1.58.0 | libboost-program-options1.62.0 | libboost-program-options1.67.0 | libboost-program-options1.71.0" - if executed on the same ubuntu release as compiled this should be in the list. Actually it should depend on that version which comes with libboost-all-dev (which is installed for compilation), but that would require all boost headers which is not the right solution.

**Comment by tobiasherzke** [comment]
See #8
