### ISSUE TITLE
missing tags for releases

### ISSUE THREAD

**Issue by dvzrv** [HoerTech-gGmbH/tascar#5]
Hi! I would like to package tascar for Arch Linux in its [community] repository.

Unfortunately there are no source tarballs to build from as none of [the releases referred to on the website](http://news.tascar.org/index.html) are reflected in tags in this repository.

It would be really great if you could add them, as this would allow any downstream distribution to build this software from source without in a transparent and unproblematic way (using the automatically generated source tarballs, based on the tags, that are offered by github). :)

**Comment by gisogrimm** [comment]
Thanks! Currently the releases are packaged based on a different repository - exactly the same code, but different version history. I will try to switch to this repository for new releases (and would release a version once this switch is performed).

**Comment by gisogrimm** [comment]
From now on releases should be indicated by appropriate tags.

**Comment by dvzrv** [comment]
cool, thank you! :)
