### ISSUE TITLE
-d flag in tascar_renderfile is invalid

### ISSUE THREAD

**Issue by hendrikkayser** [HoerTech-gGmbH/tascar#7]
It sems that in commit [228d8bc](https://github.com/HoerTech-gGmbH/tascar/commit/228d8bc634a172215b08773237f2a3771d7abcc7#diff-3715744768493766d7b95f257487719a28f2601fe57c3eb66831c692728f4bf2) the 'dynamic' option got lost such that the -d flag is regarded invalid.

**Comment by gisogrimm** [comment]
The dynamic rendering is now default. This can be changed with the `--static` flag. See `tascar_renderfile -h` for details.

**Comment by hendrikkayser** [comment]
Thanks, this was not obvious to me and makes some available tools fail, e.g., scripts used in tutorials 2 and 4 from this repository and also the tools provided with https://zenodo.org/record/3905920. Any chance to keep backwards compatibility here?

**Comment by gisogrimm** [comment]
This is now fixed with commit a3df84e22dae1cc400f77db1d95aa82e85f5e558.
